import themes from "daisyui/theme/object";
import "./globals.css";
import { Theme } from "./provider/theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


console.log(themes);

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body>
        <Theme children={children}></Theme>
      </body>
    </html>
  );
}
