import DashboardLayout from "../libs/ui/dashboard-layout";


export const metadata = {
  title: "VectorPay - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <main className={`h-full antialiased`}>
        <div className="min-h-full">
            <DashboardLayout children={children}/>
        </div>
        
      </main>
    
  );
}
