"""models updated again

Revision ID: 13a757116368
Revises: 82110e833755
Create Date: 2026-09-25 08:54:49.298592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a757116368'
down_revision: Union[str, Sequence[str], None] = '82110e833755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loginAt', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('users', 'lastSpentDate',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lastSpentDate',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('users', 'loginAt')
    # ### end Alembic commands ###
