"""transactions table modified

Revision ID: 14bf245aaee5
Revises: 
Create Date: 2026-08-07 07:20:44.606491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14bf245aaee5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.Enum('DEPOSIT', 'TRANSFER', 'WITHDRAW', name='transactiontype'), nullable=False))
    op.add_column('transactions', sa.Column('senderId', sa.Uuid(), nullable=False))
    op.alter_column('transactions', 'recipientId',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_transactions_recipientId'), 'transactions', ['recipientId'], unique=False)
    op.create_index(op.f('ix_transactions_senderId'), 'transactions', ['senderId'], unique=False)
    op.drop_constraint(op.f('transactions_userId_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['recipientId'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['senderId'], ['id'])
    op.drop_column('transactions', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_userId_fkey'), 'transactions', 'users', ['userId'], ['id'])
    op.drop_index(op.f('ix_transactions_senderId'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipientId'), table_name='transactions')
    op.alter_column('transactions', 'recipientId',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('transactions', 'senderId')
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
