"""reference updated 3

Revision ID: 247c0fd426f6
Revises: 48a6cf02b231
Create Date: 2026-09-01 06:11:59.954467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '247c0fd426f6'
down_revision: Union[str, Sequence[str], None] = '48a6cf02b231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transactions', ['reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    # ### end Alembic commands ###
