"""kycStatus in the USER column updated to the kyc table status column

Revision ID: 279ba2a6ab95
Revises: 8cc8d39beba8
Create Date: 2026-09-12 09:34:07.650048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '279ba2a6ab95'
down_revision: Union[str, Sequence[str], None] = '8cc8d39beba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kycStatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kycStatus', postgresql.ENUM('PENDING', 'VERIFIED', 'DECLINED', 'UNVERIFIED', name='kycstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
