"""transaction table updated

Revision ID: 327b13602964
Revises: 372d1d6e3321
Create Date: 2026-08-07 08:01:31.277982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '327b13602964'
down_revision: Union[str, Sequence[str], None] = '372d1d6e3321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_recipientId'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_senderId'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_senderId'), 'transactions', ['senderId'], unique=False)
    op.create_index(op.f('ix_transactions_recipientId'), 'transactions', ['recipientId'], unique=False)
    # ### end Alembic commands ###
