"""transactions table modified

Revision ID: 372d1d6e3321
Revises: 38200025fccc
Create Date: 2026-08-07 07:37:45.808930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '372d1d6e3321'
down_revision: Union[str, Sequence[str], None] = '38200025fccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'narration',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'narration',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
