"""transactions table modified

Revision ID: 38200025fccc
Revises: e2428d42178d
Create Date: 2026-08-07 07:28:46.201656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38200025fccc'
down_revision: Union[str, Sequence[str], None] = 'e2428d42178d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'senderId',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('transactions', 'recipientId',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'recipientId',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transactions', 'senderId',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
