"""marketing column  updated and biometrics column added

Revision ID: 41e3c3531f2b
Revises: e424ea9b1d10
Create Date: 2026-09-22 03:20:58.833911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41e3c3531f2b'
down_revision: Union[str, Sequence[str], None] = 'e424ea9b1d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isMarketingEnabled', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('isBiometricsEnabled', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'marketing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('marketing', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'isBiometricsEnabled')
    op.drop_column('users', 'isMarketingEnabled')
    # ### end Alembic commands ###
