"""loginAt column

Revision ID: 441b46d982c1
Revises: 41e3c3531f2b
Create Date: 2026-09-23 13:00:05.906623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '441b46d982c1'
down_revision: Union[str, Sequence[str], None] = '41e3c3531f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loginAt', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'loginAt')
    # ### end Alembic commands ###
