"""transaction pin field added

Revision ID: 500efe00c272
Revises: 75e0c1ef8011
Create Date: 2026-07-09 06:04:53.181567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '500efe00c272'
down_revision: Union[str, Sequence[str], None] = '75e0c1ef8011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transactionPin', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transactionPin')
    # ### end Alembic commands ###
