"""kyc table updated

Revision ID: 53e0c79b0b37
Revises: cfedc5dca1b3
Create Date: 2026-09-03 11:00:23.624204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53e0c79b0b37'
down_revision: Union[str, Sequence[str], None] = 'cfedc5dca1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('kyc', sa.Column('date', postgresql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'date')
    op.drop_column('kyc', 'reason')
    # ### end Alembic commands ###
