"""kyc table

Revision ID: 67f6751defe0
Revises: cac4b79cd767
Create Date: 2026-07-27 14:46:40.880061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67f6751defe0'
down_revision: Union[str, Sequence[str], None] = 'cac4b79cd767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'kyc', 'users', ['userId'], ['id'])
    op.add_column('users', sa.Column('kycStatus', sa.Enum('PENDING', 'VERIFIED', 'DECLINED', 'UNVERIFIED', name='kycstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kycStatus')
    op.drop_constraint(None, 'kyc', type_='foreignkey')
    # ### end Alembic commands ###
