"""kyc table updated

Revision ID: 763550a4a233
Revises: 53e0c79b0b37
Create Date: 2026-09-03 11:22:53.921694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '763550a4a233'
down_revision: Union[str, Sequence[str], None] = '53e0c79b0b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'DECLINED', 'UNVERIFIED', name='kycstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'status')
    # ### end Alembic commands ###
