"""transaction pin field added

Revision ID: 83192e10ddad
Revises: 500efe00c272
Create Date: 2026-07-09 06:33:22.270317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83192e10ddad'
down_revision: Union[str, Sequence[str], None] = '500efe00c272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'transactionPin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'transactionPin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
