"""transaction table updated

Revision ID: 8d1f7e1c87cc
Revises: ecc1a7a161a5
Create Date: 2026-08-07 08:13:48.157979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d1f7e1c87cc'
down_revision: Union[str, Sequence[str], None] = 'ecc1a7a161a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
