"""kycStatus in the USER column updated to the kyc table status column

Revision ID: 9bcdd403dc45
Revises: 279ba2a6ab95
Create Date: 2026-09-12 09:49:07.640070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bcdd403dc45'
down_revision: Union[str, Sequence[str], None] = '279ba2a6ab95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
