"""models updated again 2

Revision ID: a0345f48836d
Revises: 
Create Date: 2026-09-25 09:16:48.557053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0345f48836d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc', 'userId',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'isVerified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('USER', 'ADMIN', name='roles'),
               existing_nullable=False)
    op.alter_column('users', 'lastSpentDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'isMarketingEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'isBiometricsEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isBiometricsEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'isMarketingEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'lastSpentDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='roles'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'isVerified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('kyc', 'userId',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
