"""models updated again

Revision ID: cb6d91b0321e
Revises: 
Create Date: 2026-09-25 09:59:41.117419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb6d91b0321e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kyc', 'userId',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_kyc_userId'), 'kyc', ['userId'], unique=False)
    op.alter_column('users', 'isVerified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'lastSpentDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'isMarketingEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'isBiometricsEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isBiometricsEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'isMarketingEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'lastSpentDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'isVerified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_kyc_userId'), table_name='kyc')
    op.alter_column('kyc', 'userId',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
