"""transaction table updated

Revision ID: e091f596ca9a
Revises: 62172658f431
Create Date: 2026-08-07 08:08:39.573400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e091f596ca9a'
down_revision: Union[str, Sequence[str], None] = '62172658f431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_recipientId'), 'transactions', ['recipientId'], unique=False)
    op.create_index(op.f('ix_transactions_senderId'), 'transactions', ['senderId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_senderId'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipientId'), table_name='transactions')
    # ### end Alembic commands ###
