"""alert column modified to marketing

Revision ID: e424ea9b1d10
Revises: a157f0ca6b83
Create Date: 2026-09-21 06:53:03.504169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e424ea9b1d10'
down_revision: Union[str, Sequence[str], None] = 'a157f0ca6b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('marketing', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'alert')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alert', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'marketing')
    # ### end Alembic commands ###
