"""daily limit

Revision ID: fb62e447a9d0
Revises: 6043dbd50e1d
Create Date: 2026-08-09 07:14:55.456312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb62e447a9d0'
down_revision: Union[str, Sequence[str], None] = '6043dbd50e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dailyLimit', sa.Enum('TIER_ONE', 'TIER_TWO', 'TIER_THREE', name='dailylimit'), nullable=False))
    op.add_column('users', sa.Column('dailySpent', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('lastSpentDate', postgresql.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastSpentDate')
    op.drop_column('users', 'dailySpent')
    op.drop_column('users', 'dailyLimit')
    # ### end Alembic commands ###
