
export const metadata = {
  title: "VectorPay - Onboarding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <main className={`h-full antialiased`}>
        <div className="min-h-full">
            {children}
        </div>
        
      </main>
    
  );
}
